### PR TITLE
Whole new world

### PR DESCRIPTION
**Pull request by pkaminski**
[Review on Reviewable](https://reviewable-dev-piotr.firebaseapp.com/reviews/pkaminski/sample/8)

### CODE REVIEW

**Comment by pkaminski** [comment]
Add a comment.

**Comment by pkaminski** [comment]
Another one.

**Comment by fnenu** [comment]
Comments from the [review on Reviewable.io](https://localhost:8080/reviews/pkaminski/sample/8)







---

<sup>**[bar.txt, line 1 \[r3\]](https://localhost:8080/reviews/pkaminski/sample/8#-Jk7gZNOJ2Qg_E_bzmWA)** ([raw file](https://github.com/pkaminski/sample/blob/0a31898b87edfd547ee3a14fb070a3574a1b4498/bar.txt#L1)):</sup>
boo boo boo

---

<sup>**[foo.js, line 5 \[r3\]](https://localhost:8080/reviews/pkaminski/sample/8#-Jk7gMaqkCFhzMFoVQsA)** ([raw file](https://github.com/pkaminski/sample/blob/0a31898b87edfd547ee3a14fb070a3574a1b4498/foo.js#L5)):</sup>
Glad to see they're gone.

---

<sup>**[kale.txt, line 1 \[r3\]](https://localhost:8080/reviews/pkaminski/sample/8#-Jk7gapuxjse_OqnN_bB)** ([raw file](https://github.com/pkaminski/sample/blob/0a31898b87edfd547ee3a14fb070a3574a1b4498/kale.txt#L1)):</sup>
Inspiring

---

**Comment by fnenu** [comment]
Comments from the [review on Reviewable.io](https://localhost:8080/reviews/pkaminski/sample/8)







---

<sup>**[foo.js, line 5 \[r3\]](https://localhost:8080/reviews/pkaminski/sample/8#-Jk7gMaqkCFhzMFoVQsA)** ([raw file](https://github.com/pkaminski/sample/blob/0a31898b87edfd547ee3a14fb070a3574a1b4498/foo.js#L5)):</sup>
Yes, those spaces. Bad, so bad.

---

<sup>**[kale.txt, line 1 \[r3\]](https://localhost:8080/reviews/pkaminski/sample/8#-Jk7gapuxjse_OqnN_bB)** ([raw file](https://github.com/pkaminski/sample/blob/0a31898b87edfd547ee3a14fb070a3574a1b4498/kale.txt#L1)):</sup>
Yes, yes, very!

---

<sup>**[README.md, line 12 \[r3\]](https://localhost:8080/reviews/pkaminski/sample/8#-Jk7tIYrI1RMN_sN54Ac)** ([raw file](https://github.com/pkaminski/sample/blob/63e7fc32edd1772fb2328ebcb8cb51cade688ef0/README.md#L12)):</sup>
llama llama duck!


A whole new world.
For you and meeeeeeeeeeeeeee.
The end.
 
asllaslsl

---

<sup>**[TRUE/foo.txt, line 1 \[r3\]](https://localhost:8080/reviews/pkaminski/sample/8#-Jk7vHhjSYcvBGFku4M9)** ([raw file](https://github.com/pkaminski/sample/blob/0a31898b87edfd547ee3a14fb070a3574a1b4498/TRUE/foo.txt#L1)):</sup>
I think you meant lalalalallama llama duck

---

**Comment by fnenu** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pkaminski/sample/8)







---

<sup>**[README.md, line 5 \[r3\]](https://reviewable.io:443/reviews/pkaminski/sample/8#-Jk83OrdQN74aD3WzSwu)** ([raw file](https://github.com/pkaminski/sample/blob/0a31898b87edfd547ee3a14fb070a3574a1b4498/README.md#L5)):</sup>
h

---

<sup>**[README.md, line 14 \[r3\]](https://reviewable.io:443/reviews/pkaminski/sample/8#-Jk83STmg07h62ZcnClU)** ([raw file](https://github.com/pkaminski/sample/blob/63e7fc32edd1772fb2328ebcb8cb51cade688ef0/README.md#L14)):</sup>
h

---

<sup>**[README.md, line 15 \[r3\]](https://reviewable.io:443/reviews/pkaminski/sample/8#-Jk83TRg-DdQIrLb0MWa)** ([raw file](https://github.com/pkaminski/sample/blob/63e7fc32edd1772fb2328ebcb8cb51cade688ef0/README.md#L15)):</sup>
h

---

**Comment by fnenu** [comment]
Comments from the [review on Reviewable.io](https://localhost:8080/reviews/pkaminski/sample/8)







---

<sup>**[foo.js, line 1 \[r3\]](https://localhost:8080/reviews/pkaminski/sample/8#-Jk83kIl14xO1TEIwFwP)** ([raw file](https://github.com/pkaminski/sample/blob/0a31898b87edfd547ee3a14fb070a3574a1b4498/foo.js#L1)):</sup>
checking shortcuts

---

**Comment by fnenu** [comment]
Comments from the [review on Reviewable.io](https://localhost:8080/reviews/pkaminski/sample/8)







---

<sup>**[foo.js, line 1 \[r3\]](https://localhost:8080/reviews/pkaminski/sample/8#-Jk83kIl14xO1TEIwFwP)** ([raw file](https://github.com/pkaminski/sample/blob/0a31898b87edfd547ee3a14fb070a3574a1b4498/foo.js#L1)):</sup>
response

---

**Comment by fnenu** [comment]
Comments from the [review on Reviewable.io](https://localhost:8080/reviews/pkaminski/sample/8)







---

<sup>**[bar.txt, line 1 \[r3\]](https://localhost:8080/reviews/pkaminski/sample/8#-Jk7gZNOJ2Qg_E_bzmWA)** ([raw file](https://github.com/pkaminski/sample/blob/0a31898b87edfd547ee3a14fb070a3574a1b4498/bar.txt#L1)):</sup>
something

---

**Comment by fnenu** [comment]
Comments from the [review on Reviewable.io](https://reviewable-dev-fnenu.firebaseapp.com:443/reviews/pkaminski/sample/8)







---

<sup>**[foo.js, line 5 \[r3\]](https://reviewable-dev-fnenu.firebaseapp.com:443/reviews/pkaminski/sample/8#-Jk7gMaqkCFhzMFoVQsA)** ([raw file](https://github.com/pkaminski/sample/blob/0a31898b87edfd547ee3a14fb070a3574a1b4498/foo.js#L5)):</sup>
+1

---

**Comment by fnenu** [comment]
Comments from the [review on Reviewable.io](https://reviewable-dev-fnenu.firebaseapp.com:443/reviews/pkaminski/sample/8)







---

<sup>**[foo.js, line 1 \[r3\]](https://reviewable-dev-fnenu.firebaseapp.com:443/reviews/pkaminski/sample/8#-Jk83kIl14xO1TEIwFwP)** ([raw file](https://github.com/pkaminski/sample/blob/0a31898b87edfd547ee3a14fb070a3574a1b4498/foo.js#L1)):</sup>
instant send?

---

**Comment by fnenu** [comment]
Comments from the [review on Reviewable.io](https://reviewable-dev-fnenu.firebaseapp.com:443/reviews/pkaminski/sample/8)







---

<sup>**[foo.js, line 1 \[r3\]](https://reviewable-dev-fnenu.firebaseapp.com:443/reviews/pkaminski/sample/8#-Jk83kIl14xO1TEIwFwP)** ([raw file](https://github.com/pkaminski/sample/blob/0a31898b87edfd547ee3a14fb070a3574a1b4498/foo.js#L1)):</sup>
again?

---

**Comment by fnenu** [comment]
Comments from the [review on Reviewable.io](https://reviewable-dev-fnenu.firebaseapp.com:443/reviews/pkaminski/sample/8)







---

<sup>**[foo.js, line 5 \[r3\]](https://reviewable-dev-fnenu.firebaseapp.com:443/reviews/pkaminski/sample/8#-Jk9GAdrIFICAyEDZJ4Q)** ([raw file](https://github.com/pkaminski/sample/blob/0a31898b87edfd547ee3a14fb070a3574a1b4498/foo.js#L5)):</sup>
even more?

---

**Comment by pkaminski-test** [comment]
Comments from the [review on Reviewable.io](https://localhost:8080/reviews/pkaminski/sample/8)

Reviewed files:
- bar.txt @ r2
- foo.js @ r2
- kale.txt @ r2
- README.md @ r3
- TRUE/foo.txt @ r2





---

**Pull request merged**
