### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pkaminski**
This change is [Reviewable](https://reviewable-dev-piotr.firebaseapp.com/reviews/pkaminski/sample/53)

### CODE REVIEW

**Comment by pkaminski** [comment]
A new comment on a new PR.

**Comment by pkaminski** [comment]
+(v2.0) +invalid +foo

---







*Comments from [Reviewable](http://localhost:8080/reviews/pkaminski/sample/53#-:-KF35wwo0q2ya2Krc93N:562384690)*

**Comment by pkaminski** [comment]
+(v2.0) +bug +foo

---







*Comments from [Reviewable](http://localhost:8080/reviews/pkaminski/sample/53#-:-KF371BVTlRon9vVQNjk:271425519)*

**Comment by pkaminski** [comment]
+(v2.0) +bug +foo

---







*Comments from [Reviewable](http://localhost:8080/reviews/pkaminski/sample/53#-:-KF37RPe1ReuWcz2GCi6:271425519)*

**Comment by pkaminski-test** [comment]
+invalid +bar

---







*Comments from [Reviewable](http://localhost:8080/reviews/pkaminski/sample/53#-:-KF38L529llh2ossgBC7:266514323)*

**Comment by pkaminski-test** [comment]
+qux -foo

---







*Comments from [Reviewable](http://localhost:8080/reviews/pkaminski/sample/53#-:-KF38d5LbfxK4vva6Ala:-1530471329)*

**Comment by pkaminski** [comment]
Here's a new comment to check token encryption.

**Comment by pkaminski** [comment]
Again.

**Comment by pkaminski** [comment]
And again.

**Comment by pkaminski** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](http://localhost:8080/reviews/pkaminski/sample/53)*

**Pull request merged**
